# Generated by Django 5.2.1 on 2025-05-24 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManagement',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.TextField(blank=True, max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('is_sku_manual', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
    ]
