# Generated by Django 5.2.1 on 2025-05-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_management', '0002_itemmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmanagement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
