# Generated by Django 5.2.1 on 2025-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_management', '0003_itemmanagement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmanagement',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
